{"name":"1669021615","hostname":"BRILAPNB5611","pid":3144,"level":20,"msg":"Sync server version: 1.3.8 2022-02-25 10:58:11 -0600 50659ecda06a8b79a41f24c1fdff05187324402b","time":"2022-11-21T09:06:54.750Z","v":0}
{"name":"1669021615","hostname":"BRILAPNB5611","pid":3144,"level":30,"msg":"Acquiring actors for session 1669021615: ACTOR1","time":"2022-11-21T09:06:54.760Z","v":0}
{"name":"1669021615","hostname":"BRILAPNB5611","pid":3144,"level":30,"msg":"Session 1669021615 with label \"Session 1669021347 2\" started at 2022-11-21 09:06:54 UTC","time":"2022-11-21T09:06:54.769Z","v":0}
{"name":"1669021615","hostname":"BRILAPNB5611","pid":3144,"level":30,"actorType":"ACTOR1","actorId":"4610","time":"2022-11-21T09:06:57.0929339Z","msg":"Actor 4610 of type ACTOR1 was acquired by test session 1669021615","v":0}
{"name":"1669021615","hostname":"BRILAPNB5611","pid":3144,"level":20,"actorType":"ACTOR1","actorId":"4610","time":"2022-11-21T09:06:57.1049517Z","msg":"DEBUG: Test actor JAR versions:","v":0}
{"name":"1669021615","hostname":"BRILAPNB5611","pid":3144,"level":20,"actorType":"ACTOR1","actorId":"4610","time":"2022-11-21T09:06:57.1064768Z","msg":"DEBUG:   opentest-appium-0.0.1.jar: 2022-02-25 10:58 -0600 0.0.1-50659ecda06a8b79a41f24c1fdff05187324402b-dirty","v":0}
{"name":"1669021615","hostname":"BRILAPNB5611","pid":3144,"level":20,"actorType":"ACTOR1","actorId":"4610","time":"2022-11-21T09:06:57.1064768Z","msg":"DEBUG:   opentest-base-0.0.1.jar: 2022-02-25 10:58 -0600 0.0.1-50659ecda06a8b79a41f24c1fdff05187324402b-dirty","v":0}
{"name":"1669021615","hostname":"BRILAPNB5611","pid":3144,"level":20,"actorType":"ACTOR1","actorId":"4610","time":"2022-11-21T09:06:57.1091525Z","msg":"DEBUG:   opentest-selenium-0.0.1.jar: 2022-02-25 10:58 -0600 0.0.1-50659ecda06a8b79a41f24c1fdff05187324402b-dirty","v":0}
{"name":"1669021615","hostname":"BRILAPNB5611","pid":3144,"level":40,"actorType":"ACTOR1","actorId":"4610","time":"2022-11-21T09:06:57.1091525Z","msg":"WARN: Failed to log extension JARs","v":0}
{"name":"1669021615","hostname":"BRILAPNB5611","pid":3144,"level":10,"actorType":"ACTOR1","actorId":"4610","time":"2022-11-21T09:06:57.1091525Z","msg":"TRACE: Firing SESSION_STARTED event...","v":0}
{"name":"1669021615","hostname":"BRILAPNB5611","pid":3144,"level":30,"actorType":"ACTOR1","actorId":"4610","time":"2022-11-21T09:06:57.2266184Z","msg":"==================== ACTOR1: mobile/Cricbuzzdemo ====================","v":0}
{"name":"1669021615","hostname":"BRILAPNB5611","pid":3144,"level":30,"actorType":"ACTOR1","actorId":"4610","time":"2022-11-21T09:06:57.2342821Z","msg":"Actor ACTOR1 started executing test mobile/Cricbuzzdemo...","v":0}
{"name":"1669021615","hostname":"BRILAPNB5611","pid":3144,"level":10,"actorType":"ACTOR1","actorId":"4610","time":"2022-11-21T09:06:57.2342821Z","msg":"TRACE: Firing TEST_STARTED event...","v":0}
{"name":"1669021615","hostname":"BRILAPNB5611","pid":3144,"level":30,"actorType":"ACTOR1","actorId":"4610","time":"2022-11-21T09:06:57.3001097Z","msg":"Executing segment 1 of test mobile/Cricbuzzdemo...","v":0}
{"name":"1669021615","hostname":"BRILAPNB5611","pid":3144,"level":30,"actorType":"ACTOR1","actorId":"4610","time":"2022-11-21T09:06:57.3001097Z","msg":"Evaluating action 1/14 (LaunchMobApp) in segment 1...","v":0}
{"name":"1669021615","hostname":"BRILAPNB5611","pid":3144,"level":30,"actorType":"ACTOR1","actorId":"4610","time":"2022-11-21T09:06:57.3167342Z","msg":"Executing macro LaunchMobApp (no arguments were provided)...","v":0}
{"name":"1669021615","hostname":"BRILAPNB5611","pid":3144,"level":30,"actorType":"ACTOR1","actorId":"4610","time":"2022-11-21T09:06:57.3167342Z","msg":"Evaluating action 1/1 in macro LaunchMobApp (Launch the mobile app)...","v":0}
{"name":"1669021615","hostname":"BRILAPNB5611","pid":3144,"level":30,"actorType":"ACTOR1","actorId":"4610","time":"2022-11-21T09:06:57.3167342Z","msg":"Using Appium server URL \"http://127.0.0.1:4723/wd/hub\"","v":0}
{"name":"1669021615","hostname":"BRILAPNB5611","pid":3144,"level":30,"actorType":"ACTOR1","actorId":"4610","time":"2022-11-21T09:06:57.3167342Z","msg":"Creating Appium iOS driver...","v":0}
{"name":"1669021615","hostname":"BRILAPNB5611","pid":3144,"level":40,"actorType":"ACTOR1","actorId":"4610","time":"2022-11-21T09:06:57.4450637Z","msg":"WARN: Caught a org.openqa.selenium.SessionNotCreatedException exception while initializing Appium. Retries left: 2","v":0}
{"name":"1669021615","hostname":"BRILAPNB5611","pid":3144,"level":30,"actorType":"ACTOR1","actorId":"4610","time":"2022-11-21T09:07:02.451954Z","msg":"Using Appium server URL \"http://127.0.0.1:4723/wd/hub\"","v":0}
{"name":"1669021615","hostname":"BRILAPNB5611","pid":3144,"level":30,"actorType":"ACTOR1","actorId":"4610","time":"2022-11-21T09:07:02.4537977Z","msg":"Creating Appium iOS driver...","v":0}
{"name":"1669021615","hostname":"BRILAPNB5611","pid":3144,"level":40,"actorType":"ACTOR1","actorId":"4610","time":"2022-11-21T09:07:02.6389217Z","msg":"WARN: Caught a org.openqa.selenium.SessionNotCreatedException exception while initializing Appium. Retries left: 1","v":0}
{"name":"1669021615","hostname":"BRILAPNB5611","pid":3144,"level":30,"actorType":"ACTOR1","actorId":"4610","time":"2022-11-21T09:07:07.6491049Z","msg":"Using Appium server URL \"http://127.0.0.1:4723/wd/hub\"","v":0}
{"name":"1669021615","hostname":"BRILAPNB5611","pid":3144,"level":30,"actorType":"ACTOR1","actorId":"4610","time":"2022-11-21T09:07:07.6491049Z","msg":"Creating Appium iOS driver...","v":0}
{"name":"1669021615","hostname":"BRILAPNB5611","pid":3144,"level":50,"actorType":"ACTOR1","actorId":"4610","time":"2022-11-21T09:07:07.7887644Z","msg":"ERROR: java.lang.Exception: Failed executing test mobile/Cricbuzzdemo, segment 1\r\n\tat org.getopentest.base.TestActor.executeTestSegment(TestActor.java:2208)\r\n\tat org.getopentest.base.TestActor.runOneSession(TestActor.java:3077)\r\n\tat org.getopentest.base.TestActor.runOneSession(TestActor.java:3113)\r\n\tat org.getopentest.Main.main(Main.java:20)\r\nCaused by: java.lang.RuntimeException: There was an error while executing action no. 1 (LaunchMobApp) in segment 1 of test mobile/Cricbuzzdemo.\nThe action definition was:\n{\n  \"action\": \"org.getopentest.base.MacroAction\",\n  \"macro\": \"LaunchMobApp\"\n}\r\n\tat org.getopentest.base.TestActor.executeTestSegment(TestActor.java:2142)\r\n\t... 3 more\r\nCaused by: java.lang.RuntimeException: Failed executing action org.getopentest.base.MacroAction (arguments not available because the current action instance was not populated)\r\n\tat org.getopentest.base.TestActor.executeActionByDef(TestActor.java:1872)\r\n\tat org.getopentest.base.TestActor.executeTestSegment(TestActor.java:2092)\r\n\t... 3 more\r\nCaused by: java.lang.Exception: There was an error executing macro action LaunchMobApp (no arguments were provided)\r\n\tat org.getopentest.base.TestActor.executeMacroActionByName(TestActor.java:2021)\r\n\tat org.getopentest.base.TestActor.executeActionByDef(TestActor.java:1745)\r\n\t... 4 more\r\nCaused by: java.lang.RuntimeException: There was an error while executing action no. 1 (org.getopentest.appium.LaunchApp) in macro LaunchMobApp.\nThe action definition was:\n{\n  \"action\": \"org.getopentest.appium.LaunchApp\",\n  \"description\": \"Launch the mobile app\"\n}\r\n\tat org.getopentest.base.TestActor.executeMacroActionByDef(TestActor.java:1973)\r\n\tat org.getopentest.base.TestActor.executeMacroActionByName(TestActor.java:2013)\r\n\t... 5 more\r\nCaused by: java.lang.RuntimeException: Failed executing action org.getopentest.appium.LaunchApp (arguments not available because the current action instance was not populated)\r\n\tat org.getopentest.base.TestActor.executeActionByDef(TestActor.java:1872)\r\n\tat org.getopentest.base.TestActor.executeMacroActionByDef(TestActor.java:1938)\r\n\t... 6 more\r\nCaused by: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException\r\n\tat org.getopentest.base.TestActor.executeActionByClassName(TestActor.java:1670)\r\n\tat org.getopentest.base.TestActor.executeActionByDef(TestActor.java:1749)\r\n\t... 7 more\r\nCaused by: java.lang.reflect.InvocationTargetException\r\n\tat java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)\r\n\tat java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)\r\n\tat java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)\r\n\tat java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)\r\n\tat org.getopentest.base.TestActor.executeActionByClassName(TestActor.java:1645)\r\n\t... 8 more\r\nCaused by: org.openqa.selenium.SessionNotCreatedException: Unable to create a new remote session. Please check the server log for more details. Original error: An unknown server-side error occurred while processing the command. Original error: 'null' cannot be coerced to a valid version number\nBuild info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'\nSystem info: host: 'BRILAPNB5611', ip: '192.168.0.216', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '11.0.11'\nDriver info: driver.version: IOSDriver\nremote stacktrace: UnknownError: An unknown server-side error occurred while processing the command. Original error: 'null' cannot be coerced to a valid version number\n    at getResponseForW3CError (C:\\Users\\Rajesh.A\\AppData\\Roaming\\npm\\node_modules\\appium\\node_modules\\appium-base-driver\\lib\\protocol\\errors.js:804:9)\n    at asyncHandler (C:\\Users\\Rajesh.A\\AppData\\Roaming\\npm\\node_modules\\appium\\node_modules\\appium-base-driver\\lib\\protocol\\protocol.js:380:37)\nBuild info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'\nSystem info: host: 'BRILAPNB5611', ip: '192.168.0.216', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '11.0.11'\nDriver info: driver.version: IOSDriver\r\n\tat io.appium.java_client.remote.AppiumCommandExecutor$1.createSession(AppiumCommandExecutor.java:216)\r\n\tat io.appium.java_client.remote.AppiumCommandExecutor.createSession(AppiumCommandExecutor.java:225)\r\n\tat io.appium.java_client.remote.AppiumCommandExecutor.execute(AppiumCommandExecutor.java:247)\r\n\tat org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:552)\r\n\tat io.appium.java_client.DefaultGenericMobileDriver.execute(DefaultGenericMobileDriver.java:41)\r\n\tat io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:1)\r\n\tat io.appium.java_client.ios.IOSDriver.execute(IOSDriver.java:1)\r\n\tat org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:213)\r\n\tat io.appium.java_client.AppiumDriver.startSession(AppiumDriver.java:338)\r\n\tat org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:131)\r\n\tat io.appium.java_client.DefaultGenericMobileDriver.<init>(DefaultGenericMobileDriver.java:37)\r\n\tat io.appium.java_client.AppiumDriver.<init>(AppiumDriver.java:89)\r\n\tat io.appium.java_client.AppiumDriver.<init>(AppiumDriver.java:99)\r\n\tat io.appium.java_client.ios.IOSDriver.<init>(IOSDriver.java:90)\r\n\tat org.getopentest.appium.core.AppiumHelper.createDriver(AppiumHelper.java:106)\r\n\tat org.getopentest.appium.core.AppiumHelper.createDriverWithRetries(AppiumHelper.java:127)\r\n\tat org.getopentest.appium.core.AppiumHelper.getDriver(AppiumHelper.java:198)\r\n\tat org.getopentest.appium.core.AppiumTestAction.<init>(AppiumTestAction.java:53)\r\n\tat org.getopentest.appium.LaunchApp.<init>(LaunchApp.java:14)\r\n\t... 13 more\r\nCaused by: java.lang.reflect.InvocationTargetException\r\n\tat java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\r\n\tat java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)\r\n\tat java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\r\n\tat java.base/java.lang.reflect.Method.invoke(Method.java:566)\r\n\tat io.appium.java_client.remote.AppiumCommandExecutor$1.createSession(AppiumCommandExecutor.java:193)\r\n\t... 31 more\r\nCaused by: org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command. Original error: 'null' cannot be coerced to a valid version number\nBuild info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'\nSystem info: host: 'BRILAPNB5611', ip: '192.168.0.216', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '11.0.11'\nDriver info: driver.version: IOSDriver\nremote stacktrace: UnknownError: An unknown server-side error occurred while processing the command. Original error: 'null' cannot be coerced to a valid version number\n    at getResponseForW3CError (C:\\Users\\Rajesh.A\\AppData\\Roaming\\npm\\node_modules\\appium\\node_modules\\appium-base-driver\\lib\\protocol\\errors.js:804:9)\n    at asyncHandler (C:\\Users\\Rajesh.A\\AppData\\Roaming\\npm\\node_modules\\appium\\node_modules\\appium-base-driver\\lib\\protocol\\protocol.js:380:37)\r\n\tat java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)\r\n\tat java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)\r\n\tat java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)\r\n\tat java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)\r\n\tat org.openqa.selenium.remote.W3CHandshakeResponse.lambda$errorHandler$0(W3CHandshakeResponse.java:62)\r\n\tat org.openqa.selenium.remote.HandshakeResponse.lambda$getResponseFunction$0(HandshakeResponse.java:30)\r\n\tat org.openqa.selenium.remote.ProtocolHandshake.lambda$createSession$0(ProtocolHandshake.java:126)\r\n\tat java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)\r\n\tat java.base/java.util.Spliterators$ArraySpliterator.tryAdvance(Spliterators.java:958)\r\n\tat java.base/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:127)\r\n\tat java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:502)\r\n\tat java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:488)\r\n\tat java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)\r\n\tat java.base/java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:150)\r\n\tat java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)\r\n\tat java.base/java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:543)\r\n\tat org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:128)\r\n\t... 36 more\r\n","v":0}
{"name":"1669021615","hostname":"BRILAPNB5611","pid":3144,"level":30,"actorType":"ACTOR1","actorId":"4610","time":"2022-11-21T09:07:08.3150502Z","msg":"Test session has completed","v":0}
{"name":"1669021615","hostname":"BRILAPNB5611","pid":3144,"level":10,"actorType":"ACTOR1","actorId":"4610","time":"2022-11-21T09:07:08.3150502Z","msg":"TRACE: Firing TEST_COMPLETED event...","v":0}
{"name":"1669021615","hostname":"BRILAPNB5611","pid":3144,"level":10,"actorType":"ACTOR1","actorId":"4610","time":"2022-11-21T09:07:08.3150502Z","msg":"TRACE: Firing SESSION_COMPLETED event...","v":0}
{"name":"1669021615","hostname":"BRILAPNB5611","pid":3144,"level":30,"actorType":"ACTOR1","actorId":"4610","time":"2022-11-21T09:07:08.3150502Z","msg":"Actor 4610 of type ACTOR1 with no tags is waiting to be acquired by a test session...","v":0}
{"name":"1669021615","hostname":"BRILAPNB5611","pid":3144,"level":10,"actorType":"ACTOR1","actorId":"4610","time":"2022-11-21T09:07:52.1234382Z","msg":"TRACE: Initializing test session information in the \"announce\" method...","v":0}
{"name":"1669021615","hostname":"BRILAPNB5611","pid":3144,"level":10,"actorType":"ACTOR1","actorId":"4610","time":"2022-11-21T09:07:52.124437Z","msg":"TRACE: Session ID in sync server response was 1669021667; actor session ID was null","v":0}
